// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzu-P8Cj46TrlfduulAAruDtyTNz6fJ8o',
    appId: '1:790751026943:web:a2c4b0b596eea77337f6ca',
    messagingSenderId: '790751026943',
    projectId: 'dnd-character-manager-99389',
    authDomain: 'dnd-character-manager-99389.firebaseapp.com',
    storageBucket: 'dnd-character-manager-99389.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWrWuHrvqOBuo2xwXTh0E2jhEg2_k9Bg',
    appId: '1:790751026943:android:7ab5b4ee3fe3449437f6ca',
    messagingSenderId: '790751026943',
    projectId: 'dnd-character-manager-99389',
    storageBucket: 'dnd-character-manager-99389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeBhCoZ-nMHspnjBgSY1xM_Wa0hHVndqQ',
    appId: '1:790751026943:ios:75880835ddc4579e37f6ca',
    messagingSenderId: '790751026943',
    projectId: 'dnd-character-manager-99389',
    storageBucket: 'dnd-character-manager-99389.appspot.com',
    iosBundleId: 'com.ransommiranda.dndCharacterManager',
  );
}
